global:
  scrape_interval: 15s

scrape_configs:


  - job_name: 'uco-challenge-backend'
    scheme: http
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083']
