global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Microservicios Spring Boot (ajusta nombres y puertos seg√∫n tus contenedores)
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'messages-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'parameters-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'uco-challenge-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'uco-challenge-frontend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['uco-challenge-frontend:8080']

  # Observability components
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
